import { StyleSheet } from 'react-native';

const LIGHT_COLORS = {
    primary: '#0056A8',
    background: '#F5F7FB',
    white: '#FFFFFF',
    textDark: '#333333',
    textGrey: '#666666',
    border: '#E0E4EC',
    danger: '#D32F2F',
    success: '#4CAF50',
    warning: '#F6B800',
};

const DARK_COLORS = {
    primary: '#6AA9FF',
    background: '#0F1419',
    white: '#1F2328',
    textDark: '#ECEDEE',
    textGrey: '#A0A7B1',
    border: '#3A3F47',
    danger: '#FF6B6B',
    success: '#51CF66',
    warning: '#FFD43B',
};

export const getStyles = (colorScheme?: string | null) => {
    const isDark = colorScheme === 'dark';
    const colors = isDark ? DARK_COLORS : LIGHT_COLORS;

    return StyleSheet.create({
        container: { flex: 1, backgroundColor: colors.background, paddingHorizontal: 16, paddingTop: 16, paddingBottom: 24 },
        screenTitle: { marginBottom: 16, fontWeight: '700', textTransform: 'uppercase', color: colors.primary, fontSize: 20 },
        searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.white, marginBottom: 16, paddingHorizontal: 12, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: colors.border, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 4, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
        searchIcon: { marginRight: 10 },
        searchInput: { flex: 1, fontSize: 16, color: colors.textDark },
        listContent: { paddingBottom: 24 },
        attendeesHeader: { marginBottom: 12, gap: 6 },
        attendeesEventTitle: { fontSize: 16, fontWeight: '700', color: colors.textDark },
        attendeesCount: { fontSize: 13, color: colors.textGrey },
        attendeeCard: { backgroundColor: colors.white, borderRadius: 12, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: colors.border, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
        attendeeName: { fontSize: 15, fontWeight: '700', color: colors.textDark },
        attendeeAge: { marginTop: 4, fontSize: 13, color: colors.textGrey },
        card: { backgroundColor: colors.white, borderRadius: 12, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: colors.border, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
        cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
        eventTitle: { flex: 1, marginRight: 8, fontWeight: '700', fontSize: 18, color: colors.primary },
        statusBadge: { backgroundColor: isDark ? '#1A3A52' : '#E3F2FD', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, alignSelf: 'flex-start', borderWidth: 1, borderColor: isDark ? '#4A7BA7' : '#BBDEFB' },
        statusText: { color: colors.primary, fontSize: 12, fontWeight: '600' },
        inlineStatusBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, alignSelf: 'flex-start', marginTop: 4, backgroundColor: isDark ? '#1A3A52' : '#E3F2FD' },
        row: { flexDirection: 'row', marginBottom: 8, alignItems: 'center' },
        label: { width: 80, fontWeight: '600', fontSize: 13, color: colors.textGrey },
        value: { flex: 1, fontSize: 13, color: colors.textDark, fontWeight: '500' },
        footerButton: { marginTop: 16, alignSelf: 'stretch', backgroundColor: colors.white, borderWidth: 1, borderColor: colors.primary, borderRadius: 8, paddingVertical: 10, alignItems: 'center' },
        footerButtonText: { color: colors.primary, fontWeight: '600', fontSize: 14 },
        attendeesButton: { marginTop: 16, backgroundColor: colors.primary, paddingVertical: 10, paddingHorizontal: 16, borderRadius: 8, alignItems: 'center' },
        attendeesButtonText: { color: isDark ? colors.background : '#FFFFFF', fontWeight: '600', fontSize: 14 },
        modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 40 },
        modalCard: { width: '100%', maxWidth: 420, maxHeight: '85%', borderRadius: 16, backgroundColor: colors.white, overflow: 'hidden', flexDirection: 'column', shadowColor: "#000", shadowOpacity: 0.1, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 5 },
        modalHeader: { backgroundColor: colors.background, paddingHorizontal: 20, paddingTop: 20, paddingBottom: 20, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.border },
        modalImage: { width: 60, height: 60, marginRight: 16, borderRadius: 8, backgroundColor: colors.white },
        modalTitle: { flex: 1, color: colors.primary, fontWeight: '700', fontSize: 20, lineHeight: 24 },
        modalBody: { paddingHorizontal: 20, paddingVertical: 20, gap: 12 },
        sectionTitle: { fontWeight: '700', marginBottom: 4, color: colors.primary, fontSize: 14 },
        modalRow: { marginTop: 12 },
        registerButton: { marginTop: 20, backgroundColor: colors.primary, paddingVertical: 14, paddingHorizontal: 20, borderRadius: 10, alignItems: 'center', shadowColor: colors.primary, shadowOpacity: 0.3, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
        registerButtonText: { color: isDark ? colors.background : '#FFFFFF', fontSize: 16, fontWeight: '600', letterSpacing: 0.5 },
        unregisterButton: { marginTop: 20, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.danger, paddingVertical: 14, paddingHorizontal: 20, borderRadius: 10, alignItems: 'center' },
        unregisterButtonText: { color: colors.danger, fontSize: 16, fontWeight: '600' },
        modalCloseButton: { backgroundColor: colors.background, paddingVertical: 16, alignItems: 'center', borderTopWidth: 1, borderTopColor: colors.border },
        modalCloseButtonText: { color: colors.textGrey, fontWeight: '600', fontSize: 15 },
        successContainer: { alignItems: 'center', paddingVertical: 30, paddingHorizontal: 20 },
        successTitle: { fontSize: 22, fontWeight: '700', color: colors.primary, marginBottom: 12, textAlign: 'center' },
        successMessage: { fontSize: 16, textAlign: 'center', marginBottom: 32, lineHeight: 24, color: colors.textDark },
        undoButton: { marginTop: 0, paddingVertical: 12, paddingHorizontal: 24, backgroundColor: colors.background, borderRadius: 8, borderWidth: 1, borderColor: colors.border },
        undoButtonText: { color: colors.textGrey, fontWeight: '600' },
        timerContainer: { marginTop: 24, width: '100%', height: 6, backgroundColor: colors.border, borderRadius: 3, overflow: 'hidden' },
        timerBar: { height: '100%', backgroundColor: colors.primary },
        timerText: { textAlign: 'center', fontSize: 12, color: colors.textGrey, marginTop: 8 },
        participantsList: { width: '100%', backgroundColor: colors.background, padding: 12, borderRadius: 10, marginTop: 8, marginBottom: 16 },
        participantsTitle: { fontWeight: '700', color: colors.textDark, fontSize: 13, marginBottom: 6 },
        participantItem: { fontSize: 13, color: colors.textGrey, marginBottom: 4 },
        familySection: { marginTop: 16, padding: 12, backgroundColor: colors.background, borderRadius: 12, borderWidth: 1, borderColor: colors.border },
        familyHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
        familyAddButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary, paddingVertical: 6, paddingHorizontal: 10, borderRadius: 8, gap: 6 },
        familyAddButtonText: { color: isDark ? colors.background : '#FFFFFF', fontWeight: '600', fontSize: 12 },
        familyHint: { color: colors.textGrey, fontSize: 12 },
        familyCard: { marginTop: 10, padding: 10, borderRadius: 10, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, gap: 8 },
        familyInput: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, fontSize: 13, color: colors.textDark, backgroundColor: colors.white },
        familyRemoveButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.danger, paddingVertical: 6, paddingHorizontal: 10, borderRadius: 8, gap: 6 },
        familyRemoveButtonText: { color: isDark ? colors.background : '#FFFFFF', fontWeight: '600', fontSize: 12 },
        participantCountRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.background, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: colors.border },
        participantCountLabel: { color: colors.textGrey, fontSize: 12, fontWeight: '600' },
        participantCountValue: { color: colors.primary, fontSize: 16, fontWeight: '700' },
        centered: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
        loadingText: { marginTop: 12, fontSize: 14, color: colors.textGrey },
        errorText: { textAlign: 'center', color: colors.danger },
        emptyText: { textAlign: 'center', color: colors.textGrey, marginTop: 20 },
        debugBox: { marginTop: 12, padding: 10, borderWidth: 1, borderColor: isDark ? colors.border : '#d0d7de', borderRadius: 8, backgroundColor: isDark ? colors.background : '#f6f8fa' },
        debugTitle: { fontWeight: '700', marginBottom: 4, color: colors.textDark },
        debugItem: { fontSize: 13, color: isDark ? colors.textGrey : '#4a5568' },
        modalLoadingContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40 },
        modalLoadingText: { marginTop: 12, fontSize: 14, color: colors.textGrey },
        modalErrorContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 20, paddingHorizontal: 20 },
        modalErrorText: { textAlign: 'center', color: colors.danger, fontSize: 16, fontWeight: '600', marginBottom: 8 },
        modalErrorHint: { textAlign: 'center', color: colors.textGrey, fontSize: 14 },
        successIcon: { fontSize: 48, marginBottom: 16, textAlign: 'center' },
        infoBox: { backgroundColor: colors.background, padding: 12, borderRadius: 8, marginTop: 16, borderWidth: 1, borderColor: colors.border, alignItems: 'center' },
        infoText: { color: colors.textGrey, fontSize: 14, textAlign: 'center', lineHeight: 20 },
    });
};

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: LIGHT_COLORS.background, paddingHorizontal: 16, paddingTop: 16, paddingBottom: 24 },
});
